### ISSUE TITLE
Replace hard-coded variable lists, etc. with JSON configs

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/oeps#35]
After #36 is complete, we should look at moving any lists of variables that are hard-coded into js files into JSON files. This would be a stepping-stone to making a cleaner, more backend-driven frontend. However, I realize this would take us a bit away from the documentation for WebGeoda, so I'm looking into how/whether we should try to update that along the way.

**Comment by bucketteOfIvy** [comment]
As a bit of clarification for this issue: what specific types of variables are we interested in pulling out of JavaScript files for this issue? Is it things like `uniqueScales` from `download.JS` which could probably be moved to an outer JSON, more towards rewriting files like `csvFiles.js` to be JSON files, or both?

**Comment by mradamcox** [comment]
This has been completed. See https://github.com/healthyregions/oeps/issues/36 for a full run-down of static files that are now generated from the backend.
