### ISSUE TITLE
Record all static CSV and JSON assets needed to run front-end.

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/oeps#36]
We need to audit the current state of static CSV and JSON files that are used to drive the frontend. I believe there is content in the repo that isn't actually used anymore, so this ticket can cover removing that content, but also should produce a list (in a comment below is fine) of all files that _are_ needed.

Ultimately, the hope is that we can streamline these files and generate them directly from the backend resource definitions.

**Comment by bucketteOfIvy** [comment]
There are essentially 5 relevant files and folders:
- `meta/csvFiles.js` : used by the `download.js` filtering tool to select which files to download.
- `meta/variables.js` : `docs/index.js` references the `markdown`, `Source`, `Spatial Scale`, and `Variable Proxy` properties of each entry, as well as the overarching data category; `components/map/VariablePanel.js` retrieves relevant markdown URLs for the display variable by using the `markdownPrefix` to join `map-config.js`'s `numerator`, and `markdown` to get the actual markdown file.
- `config/variables.json' : referenced by `map-config.js` and used to control the style of the map (i.e. number of bins, variables, binning style, color scale, etc).  
- `map-config.js` : referenced by `index.js` and `default.js` to allow the map to connect geojsons to attribute data files
- `public/` : has two subdirectories, `csv/` and `geojson/` which contain the csv attribute tables and geojson geometries, respectively

With regards to unused but present files of this sort:
- `config/variables.csv`, `meta/csvFiles.csv` : appears to be csv versions of `variables.json` and `csvFiles.js`.
- `meta/docCrosswalks.js`, `meta/stateInfo.js`, `meta/zipRange.js` : files referenced by the unfinished restful API.

**Comment by mradamcox** [comment]
Turns out, the `config/variables.csv` file was actually used by `/lib/buildSpec` and `/lib/watchSpec` as the source file from which `config/variables.json` was derived. Now that that file is created from the backend app, those utilities aren't really needed anymore, and neither is `variables.csv`. All of the display-related configuration from `variables.csv` is now in `config/symbology.json`, where each variable can be given a colorScale, binning strategy, etc.

**Comment by mradamcox** [comment]
To summarize the above comments, and changes that have taken place through the course of the v2 development work (should move this table into the docs eventually):

|path|v1 use|v2 use|remove?|note|
|---|---|---|---|---|
|`map-config.js`|referenced by `index.js` and `default.js` to allow the map to connect geojsons to attribute data files|same||some aspects of the file have been changed but it still serves the same purpose|
|`config/variables.json`|referenced by map-config.js and used to control the style of the map (i.e. number of bins, variables, binning style, color scale, etc).|same||this file is now generated by the backend app, and **all** variable information is here but symbology is split out|
|`config/symbology.json`|n/a|optionally holds an entry for any variable in `variables.json` with map symbology information||new in v2|
|`config/variables.csv`|used by `/lib/buildSpec` and `/lib/watchSpec` as the source file from which `config/variables.json` was derived|unused|yes||
|`meta/csvFiles.js`|used by the download.js filtering tool to select which files to download|TBD via #32||
|`meta/csvFiles.csv`|unknown|unused|yes||
|`meta/variables.js`|docs/index.js references the markdown, Source, Spatial Scale, and Variable Proxy properties of each entry, as well as the overarching data category; components/map/VariablePanel.js retrieves relevant markdown URLs for the display variable by using the markdownPrefix to join map-config.js's numerator, and markdown to get the actual markdown file.|unused|yes|now handled by different files, esp. `config/variables.json`|
|`meta/docCrosswalks.js`|linked CSV files with documentation|unused|yes|now this is handled with `variables.json`|
|`meta/stateInfo.js`|used by REST API (unfinished)|unused||retain these files and the API itself, for potential future use|
|`meta/zipRange.js`|used by REST API (unfinished)|unused||retain these files and the API itself, for potential future use|
|`public/csv/*`|holds CSV files used to join attributes to the map|same||these files are now all automatically generated by the backend app|
|`public/geojson/*`|holds geojson files used for the map|same||note that two of the map layers, tracts and zip codes, are not store as geojson but are tilesets in Mapbox|
