### ISSUE TITLE
Upgrade NextJS to >=13.5 < 14

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/oeps#45]
The OEPS explorer app is built with NextJS, and we are using NextJS 12. We should upgrade this to >=13.5 < 14. This will force the issue of handling the warning that currently appears when you start the dev server:

```
warn  - Invalid next.config.js options detected: 
[1]   - The root value has an unexpected property, target, which is not in the list of allowed properties
```

There is a good chance that upgrading to 13.5 will produce new warnings, so please handle those as best as you can at the same time. If the upgrade causes more complex build issues, then make a new ticket... We should work through those issues before another release can be made.

Potentially helpful extra context: In the SDOH & Place NextJS app (which is at 13.5), we use `export: "output"` that is, I believe, related to the old `target` property. Because we _are_ using API endpoints within the explorer app, we cannot use `export: "output"` (because that generates a simple, static output, no server-side API routes allows).

**Comment by bodom0015** [comment]
Things appear to have gone pretty smoothly with the upgrade :+1:

I'm still testing some functions on a few of the pages to make sure that no new quirks have popped up here
