### ISSUE TITLE
Change SDOH/Neighborhood Type colors

### ISSUE THREAD

**Issue by Makosak** [healthyregions/oeps#70]
SDOH Composite index Neighborhood Type is currently set to graduated color scheme. Please change to "categorical" color scheme.

**Comment by mradamcox** [comment]
Used Color Brewer to get a palette and then muted the red into pink. This is defined in the `NeighbTyp` entry in `config/symbology.json`.

![image](https://github.com/user-attachments/assets/f63833b6-ebec-428e-ba7d-47c658ea8b9f)

#8dd3c7
#ffffb3
#bebada
#fb8072
#80b1d3
#fdb462
#b3de69

[141,211,199],
[255,255,179],
[190,186,218],
[255,204,204],
[128,177,211],
[253,180,98],
[179,222,105]
